[package]
name = "top_dog"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
specs-derive = "0.4"
shred = {version = "0.9.2", features = ["nightly"]}

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
