[package]
name = "top_dog"
version = "0.1.0"
authors = ["Dom Cristaldi, Julius Lee"]
edition = "2018"
description = "Game Jam Game Yo"

[package.metadata.bundle]
name = "top_dog"
identifier = "com.topdog.client"
resources = ["/resources"]


[dependencies]
amethyst = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
specs-derive = "0.4"

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]

default = ["vulkan"]